if has('gui_running')
    set guioptions-=rL
endif

set noswapfile
set encoding=UTF-8

set list

set hlsearch incsearch
let hicolor=" ctermbg=none cterm=bold ctermfg=10"
execute "highlight Search".hicolor
execute "highlight MatchParen".hicolor

set ignorecase smartcase

set number
set cursorline

set cindent
set expandtab shiftround softtabstop=4 shiftwidth=4

set foldmarker={,} foldmethod=marker foldlevel=1
set wildmode=list:longest wildmenu

set hidden
set autoread autowriteall

set runtimepath+=/usr/local/opt/fzf

set iskeyword=a-z,A-Z,48-57,_

if executable('ag') 
    set grepprg=ag\ --nogroup\ --nocolor\ --column
    set grepformat=%f:%l:%c%m
endif

call plug#begin('~/.vim/plugged')

" code generate
Plug 'SirVer/ultisnips'
Plug 'chrisyue/my-snips'

" expanding html abbreviations, like zencode
Plug 'mattn/emmet-vim' 

" use omni to complete method
Plug 'shawncplus/phpcomplete.vim'

Plug 'scrooloose/nerdtree'

Plug 'machakann/vim-swap'
Plug 'Townk/vim-autoclose'
Plug '/usr/local/opt/fzf'

Plug 'arnaud-lb/vim-php-namespace'

" comment
Plug 'tomtom/tlib_vim'
Plug 'tomtom/tcomment_vim'

call plug#end()

filetype plugin on

nnoremap <C-S> :grep <cword><CR>

" tags
set tags=tags.src,tags.vendor,tags.lib
autocmd BufWritePost src/*.php silent execute "!ctags -f tags.src src"
autocmd BufWritePost lib/*.php silent execute "!ctags -f tags.lib lib"
