if has('gui_running')
    set guioptions-=rL
    set guifont=Hack_Nerd_Font
endif

set noswapfile
set encoding=UTF-8

set list

set hlsearch incsearch
let hicolor=" ctermbg=none cterm=bold ctermfg=10"
execute "highlight Search".hicolor
execute "highlight MatchParen".hicolor

set ignorecase smartcase

set number
set cursorline

set ruler

set cindent
set expandtab shiftround softtabstop=4 shiftwidth=4

set foldmarker={,} foldmethod=marker foldlevel=1

set wildmode=list:longest wildmenu

set completeopt=longest,menu

set hidden
set autoread autowriteall

set runtimepath+=/usr/local/opt/fzf

set iskeyword=a-z,A-Z,48-57,_

if executable('ag') 
    set grepprg=ag\ --nogroup\ --nocolor\ --column
    set grepformat=%f:%l:%c%m
endif

call plug#begin('~/.vim/plugged')

Plug 'SirVer/ultisnips'
Plug 'chrisyue/my-snips'

Plug 'shawncplus/phpcomplete.vim'

Plug 'scrooloose/nerdtree'

Plug 'Townk/vim-autoclose'
Plug '/usr/local/opt/fzf'

Plug 'arnaud-lb/vim-php-namespace'

Plug 'tomtom/tlib_vim'
Plug 'tomtom/tcomment_vim'
let g:tcomment_maps=0

Plug 'machakann/vim-swap'

call plug#end()

filetype plugin on

colorscheme darkblue

nnoremap <C-S> :grep <cword><CR>
nnoremap <C-N> :NERDTreeFocus<CR>
nnoremap <C-K> :TComment<CR>
vnoremap <C-K> :TComment<CR>

" tags
set tags=tags.src,tags.vendor,tags.lib
autocmd BufWritePost src/*.php silent execute "!ctags -f tags.src src"
autocmd BufWritePost lib/*.php silent execute "!ctags -f tags.lib lib"
